version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: ./docker/go/Dockerfile
        tty: true
        ports:
            - 8080:8080
        volumes:
            - .:/go/src

    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: evinote
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
            container_name: mysql
        volumes:
            - "./storage/mysql:/var/lib/mysql"
